spring:
  application:
   name: order-service

server:
  port: 8080


inventory:
  base-url: ${INVENTORY_BASE_URL:http://localhost:8081}
  connect-timeout: 1s
  read-timeout: 2s

logging:
  level:
    root: INFO
    com.shirin.orderservice: DEBUG

resilience4j:
  retry:
    instances:
      inventory-service:
        max-attempts: 4

        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 5s

        enable-randomized-wait: true
        randomized-wait-factor: 0.5

        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
