syntax = "proto3";

package unarycall.v1;

option java_multiple_files = true;
option java_outer_classname = "UnaryCallProto";
option java_package = "com.shirin.unaryservicecall.grpc.v1";


enum DriverStatus{
  DRIVER_STATUS_UNSPECIFIED = 0;
  DRIVER_STATUS_AVAILABLE = 1;
  DRIVER_STATUS_BUSY = 2;
}


message Driver{
  int64 id = 1;
  string name = 2;
  DriverStatus status = 3;
  double driver_latitude = 4;
  double driver_longitude = 5;
}

message FindNearestDriverRequest{
  double passenger_latitude = 1;
  double passenger_longitude = 2;
}

message FindNearestDriverResponse{
  Driver driver = 1;
}

service DriverService {

  //gRPC Client: ride-service
  // gRPC Server: driver-service
  rpc FindDriver(FindNearestDriverRequest)
      returns (FindNearestDriverResponse);
}